@startmindmap
'https://plantuml.com/mindmap-diagram

<style>
mindmapDiagram {
  .green {
    BackgroundColor lightgreen
  }
  :depth(1) {
    BackGroundColor lightblue
  }
}
</style>

title Карта навыков

left side

* Android Basic <<green>>

** Верстка интерфейсов и разработка UI элементов
*** Разрабатывать эффективные и быстрые списки с различными типами ячеек, swipe-to-dismiss механиками и другими фичами, используя класс RecyclerView
**** 23,24
**** ДЗ 12
*** Анимировать UI используя ValueAnimator
**** 25
*** Рисовать высокопроизводительные View используя Canvas Api
**** 18
*** Создавать составные View, используя набор стандартных виджетов
**** 18
*** Верстать UI  используя различные ViewGroup: LinearLayout, ConstraintLayout и другие сабклассы View, которые предоставляет Android SDK и популярные библиотеки
**** 16
**** ДЗ 10
*** Использовать Material Design 3 согласно гайдлайнам Google
**** 19
**** ДЗ 10
*** Работа с ресурсами
**** Использовать различные типы ресурсов в Android проекте
**** 15
*** Правильно организовывать темы и стили, использовать аттрибуты темы для быстрых централизованных изменений цветовой схемы
**** 17
**** ДЗ 10
*** Работать со строками в одной/нескольких локалях
**** 15
*** Использовать формат Android Vector Drawable для векторной графики
**** 17

** Тестирование
*** Покрывать код Unit, интеграционными и e2e тестами с JUnit + Mockito, используя best practices по структуре тестов и методам тестирования
**** 41, 43
**** ДЗ 19

** Инструменты разработки
*** Настраивать и эффективно использовать IDE Android Studio
**** 14
*** Создавать и настраивать android эмулятор для тестирования приложений
**** 14
*** Понимать базовую структуру проекта и систему сборка Gradle
**** 14
*** Использовать Git для организации проектных файлов
**** 3
*** Использовать различные профилировщики и дебаггер для отладки приложений
**** 14

** Работа в фоне
*** Использовать различные вариации Service для работы в фоне приложения
**** 37
*** Правильно использовать инструменты WorkManager и AlarmManager для реализации кронов
**** 38

** Сенсоры и камера
*** Использовать hardware утилиты(сенсоры/камера) девайса для реализации различной функциональности
**** 40
**** ДЗ 18

right side

** Kotlin и основы Computer Science
*** Освоить базовый синтаксис языка Kotlin
**** 2
**** ДЗ 1
*** Освоить систему типов Kotlin
**** 4
*** Реализовывать функции, работать с исключениями
**** 5
**** ДЗ 2
*** Использовать основные структуры данных реализованные на kotlin: массивы, списки, ассоциативные массивы и множества
**** 6
**** ДЗ 3
*** Создавать различные типы классов: абстрактные, data, sealed, value и другие
**** 7
**** ДЗ 4
*** Освоить уникальные особенности Kotlin - делегирование, inline-функции, scope-функции, паттерны проектирования
**** 8
**** ДЗ 5
*** Освоить обобщенные типы и функции
**** 9
**** ДЗ 6

** Activity и Fragment
*** Создавать и запускать свои Activity используя явные и неявные экземпляры класса Intent, пробрасывать данные между Activity в двух направлениях
**** 10
**** ДЗ 7
*** Использовать различные флаги при отправке Intent и моды при запуске Activity
**** 10
**** ДЗ 8
*** Конфигурировать AndroidManifest файл, декларируя в нем компоненты, разрешения, intent-фильтры и другие тэги
**** 10,12
*** Правильно запрашивать разрешения для приложений используя Result API
**** 12
**** ДЗ 9
*** Использовать методы жизненного цикла Activity для решения различных задач, например, сохранения/восстановления состояния
**** 13
*** Использовать Fragment как основу для реализации экранов
**** 20,21
**** ДЗ 11
*** Пользоваться библиотекой Jetpack Navigation для навигации по экранам приложения
**** 22
**** ДЗ 13

** Проектирование и реализация архитектуры приложений
*** Использовать Hilt для организации DI в монолитном приложении
**** 30
**** ДЗ 15
*** Использовать стек Android Architecture Components: ViewModel, LiveData, Lifecycle
**** 27
**** ДЗ 15
*** Проектировать архитектуру приложений используя архитектуру MVVM на компонентах из Android Architecture Components
**** 27

** Асинхронное и многопоточное программирование
*** Понимать необходимость асинхронной работы в Android приложениях
*** Использовать kotlin корутины и suspend функции для асинхронной работы, например, сетевых запросов и работы с диском
**** 28
**** ДЗ 14
*** Освоить основы реактивного программирования при помощи Kotlin Flow
**** 29
**** ДЗ 14

** Работа с сетью
*** Проектировать и реализовывать сетевой слой приложения с использования Retrofit(OkHttp) для походов в сеть
**** 32
**** ДЗ 17
*** Использовать библиотеки-десериализаторы для удобный работы с JSON
**** 32

** Хранение данных
*** Хранить данные на диске используя DataStore/SharedPreferences/Room
**** 34, 35

** Работа с геопозицией и картами
*** Освоить работу с получением геоданных при помощи библиотек Google
**** 39
**** ДЗ 18
*** Научиться работать с API библиотеки географических карт на основе библиотеки Google Maps
**** 39
**** ДЗ 18




@endmindmap
